#!/bin/bash

# ===================================
# VigilCD Complete Setup Script
# ===================================
# Initializes configuration, environment, and permissions
# Auto-detects Docker GID for seamless deployment

set -e

TEMPLATE="./config/config.template.yaml"
CONFIG="./config/config.yaml"
ENV_FILE=".env"
ENV_TEMPLATE=".env.template"
CONTAINER_UID=1000
CONTAINER_GID=1000

echo "🚀 VigilCD Complete Setup"
echo "================================"
echo ""

# ===================================
# 1. Check if template exists
# ===================================
if [ ! -f "$TEMPLATE" ]; then
    echo "❌ Error: Template not found: $TEMPLATE"
    exit 1
fi

# ===================================
# 2. Create config.yaml if not exists
# ===================================
if [ -f "$CONFIG" ]; then
    echo "⚠️  Warning: config.yaml already exists!"
    read -p "   Overwrite with template? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Keeping existing config.yaml"
    else
        cp "$TEMPLATE" "$CONFIG"
        echo "✅ config.yaml overwritten from template"
    fi
else
    cp "$TEMPLATE" "$CONFIG"
    echo "✅ Created config.yaml from template"
fi

chmod 644 "$CONFIG"
echo "✅ Set permissions: 644 (rw-r--r--)"

# ===================================
# 3. Detect Docker GID and setup .env
# ===================================
echo ""
echo "🐳 Docker Configuration"
echo "================================"

# Check if Docker socket exists
if [ ! -S "/var/run/docker.sock" ]; then
    echo "❌ Error: Docker socket not found at /var/run/docker.sock"
    echo "   Is Docker installed and running?"
    exit 1
fi

# Get Docker socket GID
DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
echo "✅ Docker socket found with GID: $DOCKER_GID"

# Create or update .env file
if [ -f "$ENV_FILE" ]; then
    # Check if DOCKER_GID is already set
    if grep -q "^DOCKER_GID=" "$ENV_FILE"; then
        CURRENT_GID=$(grep "^DOCKER_GID=" "$ENV_FILE" | cut -d= -f2)
        if [ "$CURRENT_GID" = "$DOCKER_GID" ]; then
            echo "✅ .env already configured correctly (DOCKER_GID=$DOCKER_GID)"
        else
            echo "⚠️  .env exists but DOCKER_GID is different:"
            echo "   Current: $CURRENT_GID"
            echo "   Detected: $DOCKER_GID"
            read -p "   Update? (y/N): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                sed -i "s/^DOCKER_GID=.*/DOCKER_GID=$DOCKER_GID/" "$ENV_FILE"
                echo "✅ Updated DOCKER_GID in .env"
            fi
        fi
    else
        echo "⚙️  Adding DOCKER_GID to existing .env"
        # Add DOCKER_GID at the top after any existing header
        if grep -q "^# VigilCD Environment" "$ENV_FILE"; then
            # Insert after header
            sed -i "/^# VigilCD Environment/a\\
\\
# --- Docker Configuration (Auto-detected) ---\\
DOCKER_GID=$DOCKER_GID" "$ENV_FILE"
        else
            # Prepend to file
            echo -e "# --- Docker Configuration (Auto-detected) ---\nDOCKER_GID=$DOCKER_GID\n\n$(cat $ENV_FILE)" > "$ENV_FILE"
        fi
        echo "✅ Added DOCKER_GID to .env"
    fi
else
    # Create new .env file
    if [ -f "$ENV_TEMPLATE" ]; then
        cp "$ENV_TEMPLATE" "$ENV_FILE"
        # Add DOCKER_GID to template
        sed -i "1i# --- Docker Configuration (Auto-detected) ---\nDOCKER_GID=$DOCKER_GID\n" "$ENV_FILE"
        echo "✅ Created .env from template with DOCKER_GID=$DOCKER_GID"
    else
        # Create from scratch
        cat > "$ENV_FILE" << EOF
# ===================================
# VigilCD Environment Configuration
# ===================================
# Auto-generated by setup.sh

# --- Docker Configuration (Auto-detected) ---
DOCKER_GID=$DOCKER_GID

# --- Git & SSH Configuration ---
VIGILCD_SSH_KEY_PATH=/home/vigilcd/.ssh/id_ed25519
REPO_BASE_PATH=/home/vigilcd/src/repos

# --- Scheduling ---
VIGILCD_CHECK_INTERVAL_MINUTES=5
VIGILCD_GIT_RETRY_COUNT=3
VIGILCD_RETRY_BACKOFF_FACTOR=2.0

# --- Deployment Timeouts ---
VIGILCD_DOCKER_TIMEOUT=300
VIGILCD_GIT_TIMEOUT=60
VIGILCD_DOCKER_DAEMON_TIMEOUT=10

# --- Logging ---
VIGILCD_LOG_LEVEL=INFO
VIGILCD_LOG_FORMAT=json

# --- Git Authentication ---
# Add your tokens below:
VIGILCD_GITHUB_TOKEN=
GITLAB_TOKEN=
BITBUCKET_TOKEN=

# --- Private Docker Registries ---
GHCR_TOKEN=
DOCKERHUB_TOKEN=
COMPANY_REGISTRY_TOKEN=

# --- GitHub Webhooks ---
VIGILCD_GITHUB_WEBHOOK_SECRET=

# ===================================
# Documentation:
# - DOCKER_GID: Auto-detected from Docker socket
# - Add your authentication tokens above
# - Never commit this file to Git!
# ===================================
EOF
        echo "✅ Created .env with DOCKER_GID=$DOCKER_GID"
    fi
fi

chmod 600 "$ENV_FILE"
echo "✅ Set .env permissions: 600 (rw-------)"

# ===================================
# 4. Create necessary directories
# ===================================
echo ""
echo "📁 Directory Setup"
echo "================================"

mkdir -p ./repos
mkdir -p ./ssh-keys
mkdir -p ./logs
mkdir -p ./config

echo "✅ Created directories: repos/, ssh-keys/, logs/, config/"

# ===================================
# 5. Set ownership for vigilcd user (UID 1000)
# ===================================
echo ""
echo "🔧 Setting Permissions"
echo "================================"

# Check if we need sudo
if [ "$EUID" -ne 0 ] && [ "$(id -u)" -ne "$CONTAINER_UID" ]; then
    echo "   ℹ️  Running with sudo to set ownership..."
    USE_SUDO="sudo"
else
    USE_SUDO=""
fi

# Set ownership
$USE_SUDO chown -R $CONTAINER_UID:$CONTAINER_GID ./ssh-keys 2>/dev/null || true
$USE_SUDO chown -R $CONTAINER_UID:$CONTAINER_GID ./repos 2>/dev/null || true
$USE_SUDO chown -R $CONTAINER_UID:$CONTAINER_GID ./logs 2>/dev/null || true

echo "✅ Ownership set to UID $CONTAINER_UID"

# Set permissions
chmod 700 ./ssh-keys 2>/dev/null || true
chmod 755 ./repos 2>/dev/null || true
chmod 755 ./logs 2>/dev/null || true

echo "✅ Directory permissions set"

# ===================================
# 6. SSH Key Setup
# ===================================
echo ""
echo "🔐 SSH Key Setup"
echo "================================"

if [ ! -f "./ssh-keys/id_ed25519" ]; then
    echo "⚠️  No SSH keys found in ./ssh-keys/"
    read -p "   Generate SSH key now? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ssh-keygen -t ed25519 -C "vigilcd-deploy" -f ./ssh-keys/id_ed25519 -N ""

        # Set correct ownership and permissions
        $USE_SUDO chown $CONTAINER_UID:$CONTAINER_GID ./ssh-keys/id_ed25519 2>/dev/null || true
        $USE_SUDO chown $CONTAINER_UID:$CONTAINER_GID ./ssh-keys/id_ed25519.pub 2>/dev/null || true
        chmod 600 ./ssh-keys/id_ed25519
        chmod 644 ./ssh-keys/id_ed25519.pub

        echo "✅ SSH key generated"
        echo ""
        echo "📋 Add this public key to GitHub:"
        echo "   → Repository Settings → Deploy Keys → Add deploy key"
        echo ""
        cat ./ssh-keys/id_ed25519.pub
        echo ""
    else
        echo "   Skipped SSH key generation"
        echo "   You can generate it later with:"
        echo "   ssh-keygen -t ed25519 -C 'vigilcd' -f ./ssh-keys/id_ed25519"
    fi
else
    echo "✅ SSH keys already exist"
    # Ensure correct permissions
    $USE_SUDO chown $CONTAINER_UID:$CONTAINER_GID ./ssh-keys/id_ed25519 2>/dev/null || true
    chmod 600 ./ssh-keys/id_ed25519 2>/dev/null || true
fi

# ===================================
# 7. Validate config.yaml
# ===================================
echo ""
echo "🔍 Validating Configuration"
echo "================================"

if command -v python3 &> /dev/null; then
    python3 - << 'PYTHON'
import yaml
import sys

try:
    with open('./config/config.yaml', 'r') as f:
        config = yaml.safe_load(f)

    if not config or 'repos' not in config:
        print("❌ Invalid config: 'repos' key missing")
        sys.exit(1)

    if len(config['repos']) == 0:
        print("⚠️  Warning: No repositories configured")
        print("   Edit config.yaml to add your repositories")
    else:
        print(f"✅ Config valid: {len(config['repos'])} repositories configured")

        # Count branches and targets
        total_branches = sum(len(repo.get('branches', [])) for repo in config['repos'])
        total_targets = sum(
            len(branch.get('targets', []))
            for repo in config['repos']
            for branch in repo.get('branches', [])
        )
        print(f"   - {total_branches} branches")
        print(f"   - {total_targets} deployment targets")

except yaml.YAMLError as e:
    print(f"❌ YAML syntax error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Validation error: {e}")
    sys.exit(1)
PYTHON
else
    echo "⚠️  Python not found, skipping validation"
    echo "   Install Python 3 to enable config validation"
fi

# ===================================
# 8. Test Docker Access (optional)
# ===================================
echo ""
echo "🧪 Testing Docker Access"
echo "================================"

if command -v docker &> /dev/null; then
    if docker ps &> /dev/null; then
        echo "✅ Docker is accessible"
        echo "   Docker version: $(docker --version)"
        if docker compose version &> /dev/null; then
            echo "   Compose version: $(docker compose version --short)"
        else
            echo "⚠️  Docker Compose not found (will use in-container version)"
        fi
    else
        echo "⚠️  Docker daemon not accessible"
        echo "   This is OK - VigilCD will use Docker from within the container"
    fi
else
    echo "ℹ️  Docker CLI not found on host (will use in-container version)"
fi

# ===================================
# 9. Final Summary
# ===================================
echo ""
echo "================================"
echo "📋 Setup Summary"
echo "================================"
echo ""

# Show file permissions
echo "File Permissions:"
echo "-----------------"
ls -lh config/config.yaml .env 2>/dev/null | awk '{print $1, $3, $4, $9}' || true
echo ""
echo "Directory Ownership:"
echo "--------------------"
ls -ld ssh-keys repos logs 2>/dev/null | awk '{print $1, $3, $4, $9}' || true

echo ""
echo "================================"
echo "✅ Setup Complete!"
echo "================================"
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Edit your repository configuration:"
echo "   vim config/config.yaml"
echo ""
echo "2. Add authentication tokens to .env:"
echo "   vim .env"
echo "   Required: VIGILCD_GITHUB_TOKEN (for private repos)"
echo ""
echo "3. Start VigilCD:"
echo "   docker-compose up -d"
echo ""
echo "4. Check logs:"
echo "   docker-compose logs -f vigilcd"
echo ""
echo "5. Access API:"
echo "   curl http://localhost:8000/health"
echo "   curl http://localhost:8000/api/status"
echo ""
echo "================================"
echo "ℹ️  Configuration Details"
echo "================================"
echo ""
echo "Container runs as:"
echo "  - User: vigilcd (UID $CONTAINER_UID)"
echo "  - Docker Group: $DOCKER_GID (auto-detected)"
echo ""
echo "Mounted paths:"
echo "  - SSH keys: /home/vigilcd/.ssh"
echo "  - Repos: /home/vigilcd/src/repos"
echo "  - Config: /home/vigilcd/src/config/config.yaml"
echo ""
echo "Environment variables:"
echo "  - DOCKER_GID: $DOCKER_GID (required for subprocess docker compose)"
echo "  - See .env for all configuration options"
echo ""
echo "================================"
echo "🔧 Troubleshooting"
echo "================================"
echo ""
echo "If you encounter permission issues:"
echo "  ./fix-permissions.sh"
echo ""
echo "If Docker GID changes (after Docker reinstall):"
echo "  ./setup.sh  # Re-run this script"
echo ""
echo "For more help:"
echo "  - Documentation: README.md"
echo "  - Logs: docker-compose logs vigilcd"
echo "  - Health: curl http://localhost:8000/health"
echo ""