name: VigilCD image build

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./VigilCD/
          file: ./VigilCD/Dockerfile
          push: true
          tags: ghcr.io/vigilcd:${{ github.event.release.tag_name }}